cmd.highlight("clear")
vim.g.colors_name = "furnisher"
hl({
  Normal = {fg = "#111111"},
	Comment = {fg = "#666666", bg = "#EBEBEB"},
	Conceal = {},
	Constant = {fg = "#111111"},
	Cursor = {bg = "#CF222C"},
	TermCursor = {link = "Cursor"},
	TermCursorNC = {link = "Cursor"},
	CursorLine = {bg = "#F1F1F1"},
	CursorColumn = {link = "CursorLine"},
	DiagnosticError = {fg = "#CF222C"},
	DiagnosticHint = {fg = "#116228"},
	DiagnosticInfo = {fg = "#086AD8"},
	DiagnosticUnderlineError = {sp = "#CF222C", undercurl = true},
	DiagnosticUnderlineHint = {sp = "#116228", undercurl = true},
	DiagnosticUnderlineInfo = {sp = "#086AD8", undercurl = true},
	DiagnosticUnderlineWarn = {sp = "#CF222C", undercurl = true},
	DiagnosticWarn = {fg = "#3F3400"},
	DiffAdd = {bg = "#DFFEE4"},
	diffAdded = {link = "DiffAdd"},
	DiffChange = {bg = "#DFFEE4"},
	diffChanged = {link = "DiffChange"},
	DiffDelete = {bg = "#FDE6E6"},
	diffRemoved = {link = "DiffDelete"},
	DiffText = {bg = "#BAFEC5"},
	Directory = {fg = "#086AD8", bold = true},
	EndOfBuffer = {fg = "#474747", bold = true},
	Error = {fg = "#CF222C", bg = "#FCD7D8"},
	ErrorMsg = {fg = "#CF222C"},
	FloatBorder = {fg = "#5E5E5E", bg = "#E8E8E8"},
	FloatBorderBottom = {fg = "#5E5E5E", bg = "#E8E8E8"},
	FloatBorderTop = {fg = "#5E5E5E", bg = "#C1C1C1"},
	FloatTitle = {fg = "#111111", bg = "#C1C1C1", bold = true},
	CursorLineFold = {link = "FoldColumn"},
	Folded = {fg = "#5E5E5E"},
	FoldColumn = {link = "Folded"},
	Identifier = {fg = "#111111"},
	Ignore = {fg = "#111111"},
	IncSearch = {bg = "#F59B00"},
	Substitute = {link = "IncSearch"},
	LineNr = {bg = "#EBEBEB", bold = true},
	CursorLineNr = {link = "LineNr"},
	LineNrAbove = {link = "LineNr"},
	LineNrBelow = {link = "LineNr"},
	MatchParen = {reverse = true},
	ModeMsg = {bold = true},
	MoreMsg = {link = "ModeMsg"},
	Title = {link = "ModeMsg"},
	MsgArea = {},
	MsgSeparator = {},
	NormalFloat = {bg = "#E8E8E8"},
	TelescopeNormal = {link = "NormalFloat"},
	NormalNC = {},
	Palette = {},
	Pmenu = {bg = "#D4D4D4"},
	PmenuSbar = {bg = "#D4D4D4"},
	PmenuSel = {bg = "#B9B9B9"},
	PmenuThumb = {bg = "#9E9E9E"},
	PreProc = {fg = "#111111"},
	Question = {},
	QuickFixLine = {fg = "#111111", bg = "#E2E2E2", bold = true},
	Search = {bg = "#FFF833", sp = "#DDBC00", underline = true},
	SignColumn = {bg = "#EBEBEB"},
	ColorColumn = {link = "SignColumn"},
	CursorLineSign = {link = "SignColumn"},
	Special = {fg = "#111111"},
	SpellBad = {fg = "#CF222C", undercurl = true},
	SpellCap = {fg = "#3F3400", undercurl = true},
	SpellLocal = {fg = "#086AD8", undercurl = true},
	SpellRare = {fg = "#1A7B82", undercurl = true},
	Statement = {fg = "#111111"},
	StatusLine = {bg = "#B9B9B9", bold = true},
	StatusLineNC = {bg = "#DDDDDD", bold = true},
	String = {fg = "#116228"},
	Boolean = {link = "String"},
	Float = {link = "String"},
	Number = {link = "String"},
	TabLine = {bg = "#D4D4D4"},
	TabLineFill = {bg = "#B9B9B9"},
	TabLineSel = {fg = "#111111", bold = true},
	TelescopeMatching = {fg = "#783EDA", bold = true, underline = true},
	TelescopeResultsComment = {fg = "#666666"},
	Todo = {bold = true},
	Type = {fg = "#111111"},
	Underlined = {sp = "#783EDA", underline = true},
	User1 = {fg = "#000000", bg = "#B9B9B9", bold = true},
	User2 = {fg = "#CF222C", bg = "#B9B9B9", bold = true},
	User3 = {fg = "#3F3400", bg = "#B9B9B9", bold = true},
	User4 = {fg = "#116228", bg = "#B9B9B9", bold = true},
	User5 = {fg = "#1A7B82", bg = "#B9B9B9", bold = true},
	User6 = {fg = "#086AD8", bg = "#B9B9B9", bold = true},
	User7 = {fg = "#783EDA", bg = "#B9B9B9", bold = true},
	User8 = {fg = "#FFFFFF", bg = "#B9B9B9", bold = true},
	Visual = {bg = "#C2D1FF"},
	VisualNOS = {link = "Visual"},
	WarningMsg = {fg = "#3F3400"},
	Whitespace = {fg = "#303030", bg = "#E2E2E2", bold = true},
	NonText = {link = "Whitespace"},
	SpecialKey = {link = "Whitespace"},
	WildMenu = {},
	WinSeparator = {fg = "#B9B9B9", bg = "#B9B9B9"},
	diffLine = {fg = "#783EDA", bold = true},
	fugitiveStagedModifier = {fg = "#116228", bold = true},
	fugitiveStagedSection = {fg = "#116228", bold = true, italic = true},
	fugitiveUntrackedHeading = {fg = "#622FB6", bold = true},
	fugitiveStagedHeading = {link = "fugitiveUntrackedHeading"},
	fugitiveUnstagedHeading = {link = "fugitiveUntrackedHeading"},
	fugitiveUntrackedModifier = {fg = "#A71922", bold = true},
	fugitiveUnstagedModifier = {link = "fugitiveUntrackedModifier"},
	fugitiveUntrackedSection = {fg = "#A71922", bold = true, italic = true},
	fugitiveUnstagedSection = {link = "fugitiveUntrackedSection"},
	["@label"] = {fg = "#783EDA", bold = true},
	["@lsp.type.variable"] = {fg = "#55279E", bold = true},
	["@lsp.type.parameter"] = {link = "@lsp.type.variable"},
	["@lsp.typemod.function.declaration"] = {link = "@lsp.type.variable"},
	["@lsp.typemod.function.local"] = {link = "@lsp.type.variable"},
	["@method_def"] = {link = "@lsp.type.variable"},
	["@tag.javascript"] = {bold = true},
	["@tag.tsx"] = {link = "@tag.javascript"},
	["@text.literal"] = {fg = "#666666", bg = "#EBEBEB"},
	["@text.note"] = {bold = true},
	["@text.reference"] = {fg = "#783EDA", bold = true},
	["@text.uri"] = {fg = "#0554AF", underline = true},
	["@type.builtin"] = {fg = "#A71922", bold = true},
	["@lsp.type.builtin"] = {link = "@type.builtin"},
	["@lsp.type.interface"] = {link = "@type.builtin"},
	["@lsp.type.type"] = {link = "@type.builtin"},
	["@lsp.type.typeParameter"] = {link = "@type.builtin"},
})
