-- G.misc.safely("now", function()
--   vim.pack.add({ "https://github.com/j-hui/fidget.nvim" }, { confirm = false })
--
--   require("fidget").setup({
--     progress = {
--       display = {
--         done_icon = " ",
--         icon_style = "Normal",
--         overrides = {
--           overseer = {
--             ttl = 10,
--             debug_style = "Constant",
--             info_style = "Constant",
--             warn_style = "Constant",
--             error_style = "Constant",
--             icon = function(now, items)
--               for _, item in ipairs(items) do
--                 local icon = item.data.icon
--                 return type(icon) == "string" and icon or icon(now, items)
--               end
--             end,
--             states = { CANCELED = { icon = "󰜺 " }, FAILURE = { icon = " " } },
--           },
--         },
--       },
--     },
--     notification = {
--       override_vim_notify = true,
--       window = { normal_hl = "Comment", winblend = 0 },
--     },
--   })
-- end)
